import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Locale = 'en' | 'fr';
export type Translate = (key: string, values?: Record<string, string | number>) => string;

const en: Record<string, string> = {
  'nav.intake':'Manager Intake','nav.launchpad':'Ticket Launchpad','nav.dashboard':'Readiness Dashboard','nav.access':'Access Review','nav.brief':'Starter Brief','nav.worklog':'Export & Reset',
  'header.transitions':'Employee transitions','header.subtitle':'One guided workflow from intake to handoff','header.security':'Data & security','header.prototype':'Prototype Simulation','header.readiness':'Readiness','header.workflow':'Workflow','header.language':'Language',
  'scenario.transfer':'Ministry Transfer','scenario.newhire':'New Hire','scenario.blank':'Start Blank','scenario.transferDesc':'Ministry transfer with access cleanup','scenario.newhireDesc':'New hire with provisioning review','scenario.blankDesc':'Clear all fields for custom entry','scenario.selected':'Selected scenario',
  'accessibility':'Accessibility','accessibility.title':'Accessibility settings','accessibility.textSize':'Text size','accessibility.contrast':'Contrast theme','accessibility.default':'Default','accessibility.high':'High contrast','accessibility.dark':'Dark','accessibility.motion':'Reduce motion','accessibility.motionDesc':'Turn off non-essential movement and transitions.','accessibility.spacing':'Increased text spacing','accessibility.spacingDesc':'Add breathing room for easier reading.','accessibility.underline':'Underline links','accessibility.focus':'Enhanced focus indicators','accessibility.reset':'Reset accessibility settings','accessibility.statement':'Accessibility statement','accessibility.statementTitle':'Accessibility statement','accessibility.statementText':'Project Nexus is designed toward WCAG Level AA accessibility. The production version would require formal accessibility testing, including keyboard, screen-reader, zoom, contrast, and user testing.','close':'Close','cancel':'Cancel',
  'status.draft-ready':'Draft ready','status.optional':'Optional','status.needs-approval':'Pending approval','status.attention':'Attention required','status.submitted':'Submitted','status.pending-approval':'Pending approval','status.in-progress':'In progress','status.waiting':'Blocked','status.not-started':'Not started','status.complete':'Complete','risk.low':'Low risk','risk.medium':'At risk','risk.high':'Blocked',
  'employee.unnamed':'Unnamed employee','employee.destination':'Destination','employee.start':'Start','employee.location':'Location','employee.roleTbd':'Role TBD','employee.manager':'Manager',
  'form.name':'Employee name','form.manager':'Manager','form.transition':'Transition type','form.role':'Role','form.startDate':'Start date','form.previous':'Previous ministry','form.new':'New ministry / team','form.generate':'Generate Transition Bundle','form.generated':'Bundle generated','form.selectTransition':'Select transition type','form.notApplicable':'Not applicable for new hires','form.requirements':'Onboarding requirements',
  'common.step':'Step {number}','common.ready':'Ready','common.tickets':'{count} tickets','common.manager':'Manager','common.signedIn':'Signed in','common.collapse':'Collapse','common.noData':'—',
  'intake.title':'Manager Intake','intake.description':'One guided intake replaces separate onboarding requests. Select a scenario or start blank — the form is the source of truth for every screen.','intake.scenario':'Scenario selector','intake.form':'Transition intake form','intake.submittedBy':'Submitted by {manager}','intake.enterManager':'Enter manager name','intake.completeness':'Intake completeness','intake.identity':'Employee identity','intake.roleDestination':'Role & destination','intake.logistics':'Logistics & location','intake.next':'What happens next','intake.nextText':'Nexus generates ticket drafts tailored to {name}’s role, location, and selected requirements — ready for review and submission.',
  'ticket.title':'Ticket Launchpad','ticket.description':'Review the generated ticket bundle, approval paths, and submission readiness.','ticket.none':'No bundle generated yet','ticket.noneDesc':'Complete the Manager Intake form and generate a transition bundle to create ticket drafts.','ticket.generated':'Generated from role-based onboarding template','ticket.templates':'ONRequest draft templates','ticket.generatedCount':'Tickets generated','ticket.needApproval':'Need approval','ticket.bundleStatus':'Bundle status','ticket.bundle':'Generated Transition Ticket Bundle','ticket.ticket':'Ticket','ticket.category':'Category','ticket.status':'Status','ticket.approval':'Approval path','ticket.action':'Action','ticket.justification':'Business justification','ticket.submit':'Submit transition bundle','ticket.submitted':'Transition bundle submitted in prototype simulation.','ticket.simulation':'Prototype simulation',
  'dashboard.title':'Readiness Dashboard','dashboard.description':'A focused view of readiness, risks, and the actions that need attention before Day 1.','dashboard.blockers':'{count} high-risk {items} must close before {date}.','dashboard.item':'item','dashboard.items':'items','dashboard.next':'Next actions','dashboard.completeAccess':'Complete access review','dashboard.startPending':'Start date pending',
  'access.title':'Access cleanup & provisioning review','access.description':'Review existing access to remove and new role-based access to provision.','brief.title':'AI Starter Brief','brief.description':'A manager-ready first-week brief generated from the transition intake.','worklog.title':'Export & Reset','worklog.description':'Export a manager-approved worklog, then end the temporary Nexus session.','footer.product':'Project Nexus · Employee Transition Readiness Hub','footer.sample':'Sample data only · No live integrations',
  'data.account':'Employee account setup','data.payrollTransfer':'Payroll transfer form','data.payrollSetup':'Payroll / employee record setup','data.training':'Training / onboarding plan','data.security':'Security review','data.laptop':'Laptop / asset request','data.drive':'Shared drive access','data.sharepoint':'SharePoint access','data.teams':'Teams channel access','data.distribution':'Distribution list access','data.mobile':'Mobile number / SIM request','data.admin':'Admin privileges','data.building':'Building access','data.printer':'Printer / FMP setup','data.removal':'Old ministry access removal','data.standardApproval':'Standard approval','data.managerApproval':'Manager approval','data.securityReview':'IT / security review','data.ownerApproval':'Data owner approval','data.facilitiesApproval':'Facilities approval','data.cyberApproval':'Cyber / security approval','data.facilities':'Facilities','data.openRequest':'Open ONRequest','data.openFacilities':'Open Facilities Request','data.openRemoval':'Open Access Removal Request',
  'template.transfer':'{name} is transferring into a {role} role at {team} starting {date}.','template.newhire':'{name} is joining {team} as a {role} starting {date}.','template.justificationTransfer':'Business justification: {name} is transferring into a {role} role at {team} at {location}, starting {date}. Access to {access} is required to support {purpose}.','template.justificationHire':'Business justification: {name} is joining {team} as a {role} at {location}, starting {date}. Access to {access} is required to support {purpose}.',
};

const fr: Record<string, string> = {
  'nav.intake':'Saisie du gestionnaire','nav.launchpad':'Centre de demandes','nav.dashboard':'Tableau de préparation','nav.access':'Révision des accès','nav.brief':'Note de départ','nav.worklog':'Exporter et réinitialiser',
  'header.transitions':'Transitions des employés','header.subtitle':'Un parcours guidé, de la saisie au transfert','header.security':'Données et sécurité','header.prototype':'Simulation de prototype','header.readiness':'Préparation','header.workflow':'Parcours','header.language':'Langue',
  'scenario.transfer':'Mutation ministérielle','scenario.newhire':'Nouvelle embauche','scenario.blank':'Commencer à vide','scenario.transferDesc':'Mutation avec révision des accès','scenario.newhireDesc':'Nouvelle embauche avec révision du provisionnement','scenario.blankDesc':'Effacer tous les champs pour une saisie personnalisée','scenario.selected':'Scénario sélectionné',
  'accessibility':'Accessibilité','accessibility.title':'Paramètres d’accessibilité','accessibility.textSize':'Taille du texte','accessibility.contrast':'Thème de contraste','accessibility.default':'Par défaut','accessibility.high':'Contraste élevé','accessibility.dark':'Sombre','accessibility.motion':'Réduire les animations','accessibility.motionDesc':'Désactive les mouvements et transitions non essentiels.','accessibility.spacing':'Espacement accru du texte','accessibility.spacingDesc':'Ajoute de l’espace pour faciliter la lecture.','accessibility.underline':'Souligner les liens','accessibility.focus':'Indicateurs de focus améliorés','accessibility.reset':'Réinitialiser les paramètres','accessibility.statement':'Déclaration sur l’accessibilité','accessibility.statementTitle':'Déclaration sur l’accessibilité','accessibility.statementText':'Project Nexus est conçu en vue de respecter les critères d’accessibilité de niveau AA des WCAG. La version de production nécessiterait des essais officiels d’accessibilité, notamment au clavier, avec un lecteur d’écran, avec agrandissement, pour le contraste et auprès des utilisateurs.','close':'Fermer','cancel':'Annuler',
  'status.draft-ready':'Brouillon prêt','status.optional':'Facultatif','status.needs-approval':'En attente d’approbation','status.attention':'Attention requise','status.submitted':'Soumis','status.pending-approval':'En attente d’approbation','status.in-progress':'En cours','status.waiting':'Bloqué','status.not-started':'Non commencé','status.complete':'Terminé','risk.low':'Risque faible','risk.medium':'À risque','risk.high':'Bloqué',
  'employee.unnamed':'Employé sans nom','employee.destination':'Destination','employee.start':'Entrée en fonction','employee.location':'Lieu','employee.roleTbd':'Poste à confirmer','employee.manager':'Gestionnaire',
  'form.name':'Nom de l’employé','form.manager':'Gestionnaire','form.transition':'Type de transition','form.role':'Poste','form.startDate':'Date d’entrée en fonction','form.previous':'Ministère précédent','form.new':'Nouveau ministère / équipe','form.generate':'Générer l’ensemble de demandes','form.generated':'Ensemble généré','form.selectTransition':'Sélectionner le type de transition','form.notApplicable':'Sans objet pour une nouvelle embauche','form.requirements':'Exigences d’intégration',
  'common.step':'Étape {number}','common.ready':'Prêt','common.tickets':'{count} demandes','common.manager':'Gestionnaire','common.signedIn':'Connecté','common.collapse':'Réduire','common.noData':'—',
  'intake.title':'Saisie du gestionnaire','intake.description':'Une seule saisie guidée remplace les demandes d’intégration distinctes. Sélectionnez un scénario ou commencez à vide : le formulaire est la source de vérité de chaque écran.','intake.scenario':'Sélecteur de scénarios','intake.form':'Formulaire de transition','intake.submittedBy':'Soumis par {manager}','intake.enterManager':'Saisissez le nom du gestionnaire','intake.completeness':'Exhaustivité de la saisie','intake.identity':'Identité de l’employé','intake.roleDestination':'Poste et destination','intake.logistics':'Logistique et lieu','intake.next':'Prochaine étape','intake.nextText':'Nexus génère des demandes adaptées au poste, au lieu et aux exigences sélectionnées de {name}, prêtes à être révisées et soumises.',
  'ticket.title':'Centre de demandes','ticket.description':'Examinez l’ensemble de demandes, les parcours d’approbation et l’état de préparation à la soumission.','ticket.none':'Aucun ensemble généré','ticket.noneDesc':'Remplissez la saisie du gestionnaire et générez un ensemble de transition pour créer des ébauches de demandes.','ticket.generated':'Généré à partir d’un modèle d’intégration axé sur le poste','ticket.templates':'Modèles d’ébauches ONRequest','ticket.generatedCount':'Demandes générées','ticket.needApproval':'Approbation requise','ticket.bundleStatus':'État de l’ensemble','ticket.bundle':'Ensemble de demandes de transition généré','ticket.ticket':'Demande','ticket.category':'Catégorie','ticket.status':'État','ticket.approval':'Parcours d’approbation','ticket.action':'Action','ticket.justification':'Justification opérationnelle','ticket.submit':'Soumettre l’ensemble de transition','ticket.submitted':'Ensemble de transition soumis dans la simulation de prototype.','ticket.simulation':'Simulation de prototype',
  'dashboard.title':'Tableau de préparation','dashboard.description':'Une vue ciblée de la préparation, des risques et des actions à traiter avant le premier jour.','dashboard.blockers':'{count} {items} à risque élevé doivent être réglés avant le {date}.','dashboard.item':'élément','dashboard.items':'éléments','dashboard.next':'Prochaines actions','dashboard.completeAccess':'Terminer la révision des accès','dashboard.startPending':'Date d’entrée en fonction à confirmer',
  'access.title':'Révision du retrait et du provisionnement des accès','access.description':'Examinez les accès existants à retirer et les accès à provisionner selon le poste.','brief.title':'Note de départ IA','brief.description':'Une note de première semaine prête pour le gestionnaire, produite à partir de la saisie de transition.','worklog.title':'Exporter et réinitialiser','worklog.description':'Exportez un registre approuvé par le gestionnaire, puis mettez fin à la session Nexus temporaire.','footer.product':'Project Nexus · Centre de préparation aux transitions d’employés','footer.sample':'Données d’exemple seulement · Aucune intégration active',
  'data.account':'Configuration du compte de l’employé','data.payrollTransfer':'Formulaire de mutation de la paie','data.payrollSetup':'Configuration de la paie / du dossier de l’employé','data.training':'Plan de formation / d’intégration','data.security':'Révision de sécurité','data.laptop':'Demande d’ordinateur portable / d’actif','data.drive':'Accès au lecteur partagé','data.sharepoint':'Accès à SharePoint','data.teams':'Accès au canal Teams','data.distribution':'Accès à la liste de diffusion','data.mobile':'Demande de numéro mobile / carte SIM','data.admin':'Privilèges d’administrateur','data.building':'Accès au bâtiment','data.printer':'Configuration de l’imprimante / FMP','data.removal':'Retrait des anciens accès ministériels','data.standardApproval':'Approbation standard','data.managerApproval':'Approbation du gestionnaire','data.securityReview':'Révision informatique / sécurité','data.ownerApproval':'Approbation du propriétaire des données','data.facilitiesApproval':'Approbation des installations','data.cyberApproval':'Approbation cybersécurité / sécurité','data.facilities':'Installations','data.openRequest':'Ouvrir ONRequest','data.openFacilities':'Ouvrir une demande aux installations','data.openRemoval':'Ouvrir une demande de retrait des accès',
  'template.transfer':'{name} est muté à un poste de {role} au {team} à compter du {date}.','template.newhire':'{name} entre en fonction au {team} à titre de {role} à compter du {date}.','template.justificationTransfer':'Justification opérationnelle : {name} est muté à un poste de {role} au {team}, à {location}, à compter du {date}. L’accès à {access} est requis pour {purpose}.','template.justificationHire':'Justification opérationnelle : {name} entre en fonction au {team} à titre de {role}, à {location}, à compter du {date}. L’accès à {access} est requis pour {purpose}.',
};

const LocaleContext = createContext<{ locale: Locale; setLocale: (locale: Locale) => void; t: Translate } | null>(null);
export function LocaleProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => localStorage.getItem('nexus-locale') === 'fr' ? 'fr' : 'en');
  useEffect(() => { document.documentElement.lang = locale; localStorage.setItem('nexus-locale', locale); }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (key: string, values: Record<string, string | number> = {}) => {
    const source = (locale === 'fr' ? fr[key] : en[key]) ?? en[key] ?? key;
    return source.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? `{${name}}`));
  }}), [locale]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}
export function useLocale() { const context = useContext(LocaleContext); if (!context) throw new Error('useLocale must be used within LocaleProvider'); return context; }
export function formatLocalizedDate(date: string, locale: Locale) { return date ? new Intl.DateTimeFormat(locale === 'fr' ? 'fr-CA' : 'en-CA', { dateStyle: 'long' }).format(new Date(`${date}T00:00:00`)) : ''; }
