import { ArrowRight, Briefcase, Building2, FolderOpen, LockKeyhole, ShieldCheck, Sparkles } from 'lucide-react';
import { useLocale } from './locale';
import { useNexus } from './store';

export default function WelcomeScreen({ onContinue, onCases }: { onContinue: () => void; onCases: () => void }) {
  const { locale, setLocale, t } = useLocale(); const { startCase } = useNexus();
  const choices = [{ id:'New Hire' as const, icon:Briefcase, title:locale==='fr'?'Commencer une nouvelle embauche':'Start New Hire', description:locale==='fr'?'Créer un dossier d’intégration pour un nouvel employé.':'Create a new employee onboarding case.' }, { id:'Ministry Transfer' as const, icon:Building2, title:locale==='fr'?'Commencer une mutation ministérielle':'Start Ministry Transfer', description:locale==='fr'?'Créer un dossier de mutation avec retrait des anciens accès et provisionnement du nouveau poste.':'Create a transfer case with access cleanup and new-role provisioning.' }];
  return <main className="nexus-welcome"><header className="nexus-welcome__header"><div className="flex items-center gap-3"><span className="nexus-welcome__mark"><ShieldCheck className="h-5 w-5" /></span><div><p className="text-sm font-semibold tracking-tight">Project Nexus</p><p className="text-xs text-[var(--text-muted)]">{t('header.readiness')}</p></div></div><div className="flex items-center gap-3"><span className="nexus-welcome__security"><LockKeyhole className="h-3.5 w-3.5" />{t('header.security')}</span><div className="nexus-welcome__language" role="group" aria-label={t('header.language')}>{(['en','fr'] as const).map(x=><button key={x} onClick={()=>setLocale(x)} aria-pressed={locale===x} className={locale===x?'is-selected':''}>{x.toUpperCase()}</button>)}</div></div></header><section className="nexus-welcome__hero" aria-labelledby="welcome-title"><div className="nexus-welcome__eyebrow"><Sparkles className="h-4 w-4" />{t('header.prototype')}</div><h1 id="welcome-title">{locale==='fr'?'Commencer une transition d’employé':'Start an employee transition'}</h1><p>{locale==='fr'?'Créez ou rouvrez un dossier de transition.':'Create or reopen a Transition Case.'}</p><div className="nexus-welcome__chooser">{choices.map(c=>{const Icon=c.icon;return <button key={c.id} className="nexus-welcome__choice" onClick={()=>{startCase(c.id);onContinue();}}><span className="nexus-welcome__choice-icon"><Icon className="h-5 w-5" /></span><span className="min-w-0 text-left"><span className="block text-sm font-semibold">{c.title}</span><span className="mt-1 block text-xs leading-5 text-[var(--text-secondary)]">{c.description}</span></span><ArrowRight className="h-4 w-4" /></button>})}<button className="nexus-welcome__choice" onClick={onCases}><span className="nexus-welcome__choice-icon"><FolderOpen className="h-5 w-5" /></span><span className="min-w-0 text-left"><span className="block text-sm font-semibold">{locale==='fr'?'Mes dossiers de transition':'My Transition Cases'}</span><span className="mt-1 block text-xs leading-5 text-[var(--text-secondary)]">{locale==='fr'?'Rouvrez les dossiers actifs, examinez les blocages et poursuivez le travail.':'Reopen active cases, review blockers, and continue previous work.'}</span></span><ArrowRight className="h-4 w-4" /></button></div><p className="nexus-welcome__note">{locale==='fr'?'Simulation de prototype : les dossiers de production seraient conservés dans un dépôt opérationnel approuvé et accessibles au moyen de l’authentification OPS.':'Prototype simulation: Production cases would be stored in an approved operational case store and accessed through OPS authentication.'}</p></section></main>;
}
